name: Build and Deploy - Merge main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Workflow
        uses: timescale/workflow-dispatch-action@main
        with:
          github-token: ${{ secrets.ORG_GITHUB_AGENTS_TOKEN }}
          owner: timescale
          repo: tiger-agents-deploy
          workflow_id: build.yaml
          ref: 'main'
          inputs: '{"repository": "tiger-salesforce-mcp-server", "sha": "${{ github.sha }}"}'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Dispatch Workflow
        uses: timescale/workflow-dispatch-action@main
        with:
          github-token: ${{ secrets.ORG_GITHUB_AGENTS_TOKEN }}
          owner: timescale
          repo: tiger-agents-deploy
          workflow_id: deploy.yaml
          ref: 'main'
          inputs: '{"repository": "tiger-salesforce-mcp-server", "sha": "${{ github.sha }}"}'

  # send-release-message:
  #   runs-on: ubuntu-latest
  #   needs: release
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0 # Fetch full history to access previous commits

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '22'
  #         cache: 'npm'

  #     - name: Install dependencies
  #       run: npm ci --legacy-peer-deps

  #     - name: Install Claude Code
  #       run: npm install -g @anthropic-ai/claude-code

  #     - name: Run Claude Code Analysis
  #       env:
  #         ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
  #         PREVIOUS_SHA: ${{ github.event.before }}
  #         SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  #         SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
  #         SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
  #       run: |
  #         # Replace placeholder in prompt file and run Claude Code
  #         sed "s/PREVIOUS_SHA_PLACEHOLDER/$PREVIOUS_SHA/g" prompt-for-slack-update.md | claude -p \
  #           --allowedTools "Bash(git log:*)" "Bash(git diff:*)" "Bash(npm run send-slack-message:*)" \
  #           --max-turns 10 \
  #           --output-format json
