name: Deploy Feature Branch
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Workflow
        uses: timescale/workflow-dispatch-action@main
        with:
          github-token: ${{ secrets.ORG_GITHUB_AGENTS_TOKEN }}
          owner: timescale
          repo: tiger-agents-deploy
          workflow_id: deploy.yaml
          ref: 'main'
          inputs: '{"repository": "tiger-salesforce-mcp-server", "sha": "${{ github.sha }}"}'
